version: "3"
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./:/srv/app
      - /srv/app/vendor
    links:
      - db:db
    env_file: .docker/.docker.env
  phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - db
        container_name: phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        restart: always
        ports:
            - 8889:80
        volumes:
            - /sessions
  db:
    image: mysql:5.7
    volumes:
      - ./.dbdata:/var/lib/mysql
    ports:
      - "13306:3306"
    environment:
      - MYSQL_DATABASE=dockerphp
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=dockerphp
      - MYSQL_PASSWORD=secret
volumes:
  .dbdata: