version: "3"
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/srv/app
      - /srv/app/vendor
    env_file: .docker/.docker.env
  phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        restart: always
        ports:
            - 8889:80
        volumes:
            - /sessions
