name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install Pygments
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex